/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_carplate_CarPlateDetection */

#ifndef _Included_com_example_carplate_CarPlateDetection
#define _Included_com_example_carplate_CarPlateDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_carplate_CarPlateDetection
 * Method:    ImageProc
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_carplate_CarPlateDetection_ImageProc
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
