/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_njsubier_roadparking_MainActivity */

#ifndef _Included_com_njsubier_roadparking_MainActivity
#define _Included_com_njsubier_roadparking_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_aiseminar_EasyPR_PlateRecognizer_stringFromJNI(JNIEnv *, jclass);
JNIEXPORT jlong JNICALL Java_com_aiseminar_EasyPR_PlateRecognizer_initPR(JNIEnv *, jclass, jstring, jstring);
JNIEXPORT jlong JNICALL Java_com_aiseminar_EasyPR_PlateRecognizer_uninitPR(JNIEnv *, jclass, jlong);
JNIEXPORT jbyteArray JNICALL Java_com_aiseminar_EasyPR_PlateRecognizer_plateRecognize(JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
